### ISSUE TITLE
矿机上下线次数多了程序会崩溃

### ISSUE THREAD

**Issue by KeenSting0712** [Char1esOrz/minerProxy#26]
2022/01/29 06:20:20 新的矿机上线了:ickv>>>0xD8A3c0076D7FDB9c1BBE4bA8fFbd490Aba0513D5
panic: runtime error: index out of range [0] with length 0

goroutine 28556 [running]:
goMinerProxy/worker.(*EthWorker).Init(0xc0000d0900, {0x7927b0, 0xc0000b6700}, 0xc0000d02b8, 0xc0000d01f0, {0xc000110048, 0x12}, 0x1, 0x0, 0x0, ...)
        /Users/charles/Documents/goMinerProxy/worker/eth_worker.go:239 +0x18cd
created by goMinerProxy/server.(*EthServer).process
        /Users/charles/Documents/goMinerProxy/server/eth_server.go:374 +0x314

**Comment by KeenSting0712** [comment]
这个问题不解决一下不敢用了，10台不到就频繁挂掉

**Comment by KeenSting0712** [comment]
https://github.com/KeenSting0712/emproxy  自己动手丰衣足食

**Comment by KISS1996** [comment]
目前最稳定的中转程序，并且带抽水功能，内置加密Github项目：https://github.com/KISS1996/minerproxy
